version: 2.1

jobs:
  debug-gpu-langsung:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.medium

    steps:
      - run:
          name: "Setup GPU & Remote Terminal"
          command: |
            # 1. Cek dulu GPU-nya ready apa kagak
            nvidia-smi
            
            # 2. Jalanin sshx buat dapet akses remote
            # Ini bakal ngasih lu URL di log CircleCI
            curl -sSf https://sshx.io/get | sh -s run
workflows:
  main:
    jobs:
      - debug-gpu-langsung